@KERNEL_HIGHERHALF   = yes
@KERNEL_DEBUG_MAXLVL = 10

@KERNEL_STACK_SIZE   = 4M
@KERNEL_KSTRUCT_SIZE = 512K

[SEGMENTATION] = enabled {
     SEGMENT_MAXCOUNT = 64
     TASKSEG_MODE = yes
}

[INTERRUPT] = enabled {
     GENERAL_MAXCOUNT = 256
}

[KASAN] = enabled
[PAGING] = enabled