#ifndef _KEYBOARD_CODES_HPP_
#define _KEYBOARD_CODES_HPP_

// Special key event data
#define INPUT_KBD_SKEY_F1      1
#define INPUT_KBD_SKEY_F2      2
#define INPUT_KBD_SKEY_F3      3
#define INPUT_KBD_SKEY_F4      4
#define INPUT_KBD_SKEY_F5      5
#define INPUT_KBD_SKEY_F6      6
#define INPUT_KBD_SKEY_F7      7
#define INPUT_KBD_SKEY_F8      8
#define INPUT_KBD_SKEY_F9      9
#define INPUT_KBD_SKEY_F10     10
#define INPUT_KBD_SKEY_F11     11
#define INPUT_KBD_SKEY_F12     12
#define INPUT_KBD_SKEY_LCTRL   13
#define INPUT_KBD_SKEY_LALT    14
#define INPUT_KBD_SKEY_LSHIFT  15
#define INPUT_KBD_SKEY_RCTRL   16
#define INPUT_KBD_SKEY_RALT    17
#define INPUT_KBD_SKEY_RSHIFT  18
#define INPUT_KBD_SKEY_NUMLOCK  19
#define INPUT_KBD_SKEY_SCRLOCK  20
#define INPUT_KBD_SKEY_CAPSLOCK 21
#define INPUT_KBD_SKEY_ESC      24

#define INPUT_KBD_SKEY_PGUP     25
#define INPUT_KBD_SKEY_PGDOWN   26
#define INPUT_KBD_SKEY_HOME     27
#define INPUT_KBD_SKEY_END      28
#define INPUT_KBD_SKEY_INSERT   29
#define INPUT_KBD_SKEY_DELETE   30

#define INPUT_KBD_SKEY_CURSOR_UP    31
#define INPUT_KBD_SKEY_CURSOR_DOWN  32
#define INPUT_KBD_SKEY_CURSOR_RIGHT 33
#define INPUT_KBD_SKEY_CURSOR_LEFT  34

#define INPUT_KBD_SKEY_CURSOR_PRTSCR 35

#define INPUT_KBD_DATA_KEYPAD        0x1000

#endif