@KERNEL_ADDRESS            = 0x200000
@KERNEL_VMADDRESS          = 0x100000000000
@KERNEL_RAMDISK_VMA        = 0x200000000000
@KERNEL_KASAN_VMA          = 0x2fa000000000

# <PAGE_SIZE>
@PAGE_SIZE               = 4K

# <LARGE_PAGE>
@USE_LARGE_PAGE          = yes
@LARGE_PAGE_SIZE         = 2M
@USE_ENORMOUS_PAGE       = yes
@ENORMOUS_PAGE_SIZE      = 1G

[X86_64] = {
    PAGE_LA = 48
}