#ifndef _ARCH_CONFIGURATIONS_HPP_
#define _ARCH_CONFIGURATIONS_HPP_

#define ARCHITECTURE_LIMIT 0xffffffffffffffff
#define ARCHITECTURE_LIMIT_BITS 64
#define WORD_SIZE 8
#define ENDIANNESS little
#define CONFIG_KERNEL_MINIMUM_ADDRESS 0x100000
#define CONFIG_KERNEL_HIGHERHALF_ADDRESS 0xffffffff80000000
#define CONFIG_PAGE_LEVEL 5

#endif